### ISSUE TITLE
Ability to have more than one kiosk app on desktop

### ISSUE THREAD

**Issue by tinbox134** [zebradog/kiosk#28]
It would be useful if we can have individual kiosk with different URL.
Alternative will be a menu choice within the screen.
Or have I missed something here?

**Comment by matt-cook** [comment]
Thanks for the feedback. Definitely a useful feature, but something we'd prefer to see implemented in the content page since the style and content of that selection menu will generally vary from project to project.   We've done this here: http://demo.zebradog.com/

If this is something you need implemented, message or email and we can discuss developing a custom branch for you.
