### ISSUE TITLE
daily restart has no effect

### ISSUE THREAD

**Issue by matt-cook** [zebradog/kiosk#86]
added a daily restart on an un-managed Chromebox for ~5 minutes later, didn't see the system restart.

**Comment by JVimes** [comment]
Happening for me, too, on an unmanaged Dell Chromebox 3010.

**Comment by JVimes** [comment]
I think this problem is because we're running in kiosk mode and [Browser.js, line 112](https://github.com/zebradog/kiosk/blob/master/src/js/browser.js#L112) calls [`chrome.runtime.reload()`](https://developer.chrome.com/extensions/runtime#method-reload) (not supported in kiosk mode) instead of [`chrome.runtime.restart()`](https://developer.chrome.com/extensions/runtime#method-restart).

> **reload**
> 
> chrome.runtime.reload()
> Since Chrome 25.
> 
> Reloads the app or extension. This method is not supported in kiosk mode. For kiosk mode, use chrome.runtime.restart() method.


> **restart**
> 
> chrome.runtime.restart()
> Since Chrome 32.
> 
> Restart the ChromeOS device when the app runs in kiosk mode. Otherwise, it's no-op.

If there is a use case for non-kiosk mode, calling `reload()` directly before `restart()` should work, since the former is then a no-op.

**Comment by matt-cook** [comment]
Thanks @JVimes. We'll test this and get it into the next release.

**Comment by matt-cook** [comment]
Fixed by 21fa22517c3415a237821e5021e779ba4dd89496
